name: Compile The New version OpenClash

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  GetLastChange:
    runs-on: ubuntu-latest
    outputs:
      currentChange: ${{ steps.GetLastChange.outputs.currentChange }}
      lastReleaseChange: ${{ steps.GetLastChange.outputs.lastReleaseChange }}
      version: ${{ steps.GetLastChange.outputs.version }}
      gitdiff: ${{ steps.GetLastChange.outputs.gitdiff }}
    steps:
      - name: Clone OpenClash dev Repository
        uses: actions/checkout@v4
        with:
          repository: 'vernesong/OpenClash'
          ref: dev

      - name: Get Last Change
        id: GetLastChange
        run: |
          lastReleaseChange=$(curl -s https://api.github.com/repos/${{ github.repository }}/releases | jq -r '.[0].tag_name' | awk -F'-' '{print $2}')
          currentChange=$(git log -1 --pretty=format:"%h")
          version=$(grep 'PKG_VERSION:=' ./luci-app-openclash/Makefile | awk -F '=' '{print $2}')
          echo "lastReleaseChange=$lastReleaseChange" >> $GITHUB_OUTPUT
          echo "currentChange=$currentChange" >> $GITHUB_OUTPUT
          echo "version=$version" >> $GITHUB_OUTPUT
          echo "gitdiff=$(git diff --stat $lastReleaseChange..HEAD)" >> $GITHUB_OUTPUT

  Compile:
    runs-on: ubuntu-latest
    needs: GetLastChange
    if: ${{ needs.GetLastChange.outputs.currentChange != needs.GetLastChange.outputs.lastReleaseChange }}
    env:
      NOW: ''
    steps:
      - name: Clone OpenClash dev Repository
        uses: actions/checkout@v4
        with:
          repository: 'vernesong/OpenClash'
          ref: dev
          path: OpenClash

      - name: Apt Update
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get update
          sudo apt-get -y install curl git tar

      - name: Install OpenWrt SDK
        run: |
          mkdir tmp
          curl -SLk --connect-timeout 30 --retry 2 "https://archive.openwrt.org/chaos_calmer/15.05.1/ar71xx/generic/OpenWrt-SDK-15.05.1-ar71xx-generic_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64.tar.bz2" -o "./tmp/SDK.tar.bz2"
          cd \tmp
          tar xjf SDK.tar.bz2
          mv "OpenWrt-SDK-15.05.1-ar71xx-generic_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64" "SDK"

      - name: Copy OpenClash Source Codes
        run: |
          mkdir tmp/SDK/package/luci-app-openclash
          cp -rf "./OpenClash/luci-app-openclash/." "./tmp/SDK/package/luci-app-openclash/"

      - name: Compile po2lmo
        run: |
          cd tmp/SDK/package/
          pushd luci-app-openclash/tools/po2lmo
          make && sudo make install
          popd

      - name: Compile OpenClash IPK
        run: |
          cd tmp/SDK
          make package/luci-app-openclash/compile V=99

      - name: Get Current Date
        run: echo "NOW=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: Move New version
        run: |
          mkdir out
          rm -rf ./out/luci-app-openclash_*
          ls -al ./tmp/SDK/bin/ar71xx/packages/base/
          mv "./tmp/SDK/bin/ar71xx/packages/base/luci-app-openclash_${{ needs.GetLastChange.outputs.version }}-beta_all.ipk" "./out/luci-app-openclash_${{ env.NOW }}-${{ needs.GetLastChange.outputs.currentChange }}-dev_all.ipk"

      - name: Release New version
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
        with:
          prerelease: true
          files: './out/luci-app-openclash_*.ipk'
          tag_name: 'v${{ env.NOW }}-${{ needs.GetLastChange.outputs.currentChange }}-dev'
          body: |
            Changes since last release:
            - Commit: ${{ needs.GetLastChange.outputs.currentChange }}
            - Version: ${{ needs.GetLastChange.outputs.version }}
            - Full Changes: [here](https://github.com/vernesong/OpenClash/compare/${{ needs.GetLastChange.outputs.lastReleaseChange }}..HEAD)
            - Changes:
            ```
            ${{ needs.GetLastChange.outputs.gitdiff }}
            ```

      - name: Upload to telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Changes since last release:
            - Commit: ${{ needs.GetLastChange.outputs.currentChange }}
            - Version: ${{ needs.GetLastChange.outputs.version }}
            - Full Changes: [here](https://github.com/vernesong/OpenClash/compare/${{ needs.GetLastChange.outputs.lastReleaseChange }}..HEAD)
            - Changes:
            ```
            ${{ needs.GetLastChange.outputs.gitdiff }}
            ```
          document: './out/luci-app-openclash_${{ env.NOW }}-${{ needs.GetLastChange.outputs.currentChange }}-dev_all.ipk'
